# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: danyblitz-bit.PhotoMetaClean
PackageVersion: 1.1.0
InstallerType: portable
Commands:
- photometaclean
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/danyblitz-bit/photo-metaclean/releases/download/v1.1.0/photo-metaclean.exe
  InstallerSha256: 2CE3A44D70B28E1D5963745711CA5572E4BF0A0FD6084A8BB46ACBFF3B6DDC30
ManifestType: installer
ManifestVersion: 1.6.0
