# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: danyblitz-bit.SiteAuditor
PackageVersion: 1.0.0
InstallerType: portable
Commands:
- siteauditor
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/danyblitz-bit/site-auditor/releases/download/v1.0.0/site-auditor.exe
  InstallerSha256: 7A1C2263FE07A9CF54F506F4F894E8DC6738C0AA3B317CF13E495B00116CE2F2
ManifestType: installer
ManifestVersion: 1.6.0
