# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: danyblitz-bit.PdfMetaClean
PackageVersion: 1.0.1
InstallerType: portable
Commands:
- pdfmetaclean
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/danyblitz-bit/pdf-metaclean/releases/download/v1.0.1/pdf-metaclean.exe
  InstallerSha256: 3D23626CA73F05949B034DD01DB737831FE7126AC45535D6824E4A499D9FFBDC
ManifestType: installer
ManifestVersion: 1.6.0
